name: docs

on:
  # trigger deployment on every push to main branch
  push:
    branches: [master]
  # trigger deployment manually
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          # fetch all commits to get last updated time or other git log info
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          # choose node.js version to use
          node-version: '20'
          cache: 'npm'

      # install dependencies if the cache did not hit
      - name: Install dependencies
        run: npm install --frozen-lockfile

      # run build script
      - name: Build site
        run: npm run build

      # delete node_modules
      - name: Remove File
        uses: JesseTG/rm@v1.0.3
        with:
          path: |
            **/node_modules

      # please check out the docs of the workflow for more details
      # @see https://github.com/crazy-max/ghaction-github-pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          # deploy to gh-pages branch
          target_branch: gh-pages
          # deploy build dir
          build_dir: build
        env:
          # @see https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
